Neos:
  Neos:
    Ui:
      resources:
        javascript:
          'Neos.Neos.UI.NetworkteamContentComments:CommentEditor':
            resource: 'resource://Networkteam.ContentComments/Public/JavaScript/Plugin.js'
    fusion:
      autoInclude:
        Networkteam.ContentComments: true
Networkteam:
  ContentComments:
    ShowInFrontend: false
